Add access to Helmi

diff --git a/nordiquest b/nordiquest
--- a/nordiquest
+++ b/nordiquest
@@ -1,6 +1,7 @@
 #%Module
 set-function	nqrun {
     env_vars=();
+    quantum_computers=();
     srun_args=();
     requirements_file="";
     py_script_path="";
@@ -13,8 +14,9 @@ set-function	nqrun {
     { 
         printf " Usage: nqrun [OPTIONS] [SRUN-OPTIONS] PYTHON_SCRIPT\n";
         printf "\n";
-        printf " Run quantum computing jobs on SLURM-managed high-perfromance computers (HPC)\n";
-        printf " Note that it prompts for API token\n";
+        printf " Run quantum computing jobs on SLURM-managed high-perfromance computers (HPC).\n";
+        printf " Note that it prompts for an API token for each quantum computer.\n";
+        printf " The API token is available in the environment as '{QUANTUM_COMPUTER_NAME}_API_TOKEN' (upper case).\n";
         printf "\n";
         printf " Options:\n";
         printf "  %-20s\t%s\n" "--env list" "Set environment variables like Var1=Value1";
@@ -22,6 +24,7 @@ set-function	nqrun {
         printf "  %-20s\t%s\n" "--python string" "Python module to load with 'module load [python module]'";
         printf "  %-20s\t%s\n" "--source-code-dir string" "the folder that stores source code on login node; default=D1";
         printf "  %-20s\t%s\n" "--virtual-env string" "the folder containing the virtual env to create if not exists and use for this job";
+        printf "  %-20s\t%s\n" "-qc|--quantum-computer list" "Set the quantum computers to connect to e.g. qal9000,helmi";
         printf "\n";
         printf " srun options:\n";
         srun --help
@@ -30,6 +33,11 @@ set-function	nqrun {
         case $1 in 
             --env)
                 env_vars+=("$2");
+                shift;
+                shift
+            ;;
+            -qc | --quantum-computer)
+                quantum_computers+=("$2");
                 shift;
                 shift
             ;;
@@ -68,17 +76,27 @@ set-function	nqrun {
             ;;
         esac;
     done;
+    if [ ${#quantum_computers[@]} -eq 0 ]; then
+        echo "at least one quantum computer e.g. qal9000 should be specified";
+        exit 1;
+    fi;
     if [ -z "$py_script_path" ]; then
         echo "the last argument should be the path to the python script";
         exit 1;
     fi;
-    read -s -r -p "Enter a valid QAL 9000 API token: " qal9000_api_token;
-    if [ -n "$qal9000_api_token" ]; then
-        env_vars+=("QAL9000_API_TOKEN='$qal9000_api_token'");
-    else
-        echo "QAL 9000 API token cannot be empty";
-        exit 1;
-    fi;
+    for qc in "${quantum_computers[@]}";
+    do
+        comp_name=$(echo $qc | tr '[:lower:]' '[:upper:]');
+        env_var="${comp_name}_API_TOKEN";
+        read -s -r -p "Enter a valid $comp_name API token: " api_token;
+        if [ -n "$api_token" ]; then
+            env_vars+=("$env_var='$api_token'");
+        else
+            echo "$comp_name API token cannot be empty";
+            exit 1;
+        fi;
+        printf "\n";
+    done;
     if [ -z "$python_env" ]; then
         python_env="$source_code_dir/nqenv";
     fi;
@@ -93,7 +111,7 @@ set-function	nqrun {
         if [ -n "$requirements_file" ]; then
             pip install -r $requirements_file;
         else
-            pip install tergite;
+            pip install tergite qiskit-iqm qiskit;
         fi
     };
     function generate_bash_script () 
